apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  namespace: gamestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
      - name: notifications-api
        image: notifications-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: RabbitMQ__Host
          valueFrom:
            configMapKeyRef:
              name: gaming-platform-config
              key: RABBITMQ_HOST